### ISSUE TITLE
Problems with git commit 

### ISSUE THREAD

**Issue by giuspugl** [litebird/litebird_sim#180]
Working on PR #160, can't push anything because i've a couple of errors related to `black` and `flake8` , not sure what 's going on here! 
```
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/Users/peppe/.cache/pre-commit/repocq0270nb/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/peppe/.cache/pre-commit/repocq0270nb/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1282, in patched_main
    patch_click()
  File "/Users/peppe/.cache/pre-commit/repocq0270nb/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1268, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/Users/peppe/.cache/pre-commit/repocq0270nb/py_env-python3/lib/python3.8/site-packages/click/__init__.py)

flake8...................................................................Failed
- hook id: flake8
- exit code: 1
```

Followed the installation guidelines provided in the documentation..

**Comment by ziotom78** [comment]
The problem should be fixed now. @giuspugl , may you please check?

**Comment by ziotom78** [comment]
I updated the dependency on black, be careful that version 22.3 changes the way `**` are formatted.
