### ISSUE TITLE
Error using save_simulation_for_madam

### ISSUE THREAD

**Issue by marcobortolami** [litebird/litebird_sim#201]
@nraffuzz and I are trying to use the `save_simulation_for_madam` function in the following way:
```
param_noise_madam = lbs.DestriperParameters(nside=nside,
                                            coordinate_system=lbs.coordinates.CoordinateSystem.Galactic,
                                            nnz=3, #compute I, Q, and U
                                            baseline_length_s=60,
                                            iter_max=100,
                                            output_file_prefix='map_madam_destriper_'+mission_time_days+'d_',
                                            return_hit_map=True,
                                            return_binned_map=True,
                                            return_destriped_map=True,
                                            return_npp=False,
                                            return_invnpp=False,
                                            return_rcond=False)

lbs.madam.save_simulation_for_madam(sim=sim,
                                    detectors=dets,
                                    params=param_noise_madam,
                                    use_gzip=False,
                                    absolute_paths=True)
```
sim is an instance of lbs.Simulation, dets is a list of DetectorInfo objects and param_noise_madam is an instance of lbs.DestriperParameters (defined above).

We have this error:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/marconi_scratch/userexternal/mbortola/litebird/e2e-simulation/scripts/e2e_simulation.py", line 447, in e2e_sim_production
    lbs.madam.save_simulation_for_madam(sim=sim,
  File "/marconi/home/userexternal/mbortola/.conda/envs/lbs_env/lib/python3.8/site-packages/litebird_sim/madam.py", line 101, in save_simulation_for_madam
    sim_template, par_template = _read_templates()
  File "/marconi/home/userexternal/mbortola/.conda/envs/lbs_env/lib/python3.8/site-packages/litebird_sim/madam.py", line 22, in _read_templates
    sim_template = template_env.get_template("madam_simulation_file.txt")
  File "/marconi/home/userexternal/mbortola/.conda/envs/lbs_env/lib/python3.8/site-packages/jinja2/environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "/marconi/home/userexternal/mbortola/.conda/envs/lbs_env/lib/python3.8/site-packages/jinja2/environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/marconi/home/userexternal/mbortola/.conda/envs/lbs_env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/marconi/home/userexternal/mbortola/.conda/envs/lbs_env/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: madam_simulation_file.txt

```
and we do not know how to solve this issue since, as far as we know, in the documentation the madam_simulation_file.txt is not mentioned.
Thank you in advance!

**Comment by giuspugl** [comment]
Also, could @ziotom78 provide a script to launch madam from CLI ? it ain't clear to me  how to call madam destriper w/ a parameter input file ...

**Comment by ziotom78** [comment]
Hi, sorry for the mess, I forgot to list the `*.txt` templates in `pyproject.toml`. I had to release a new version of the simulation framework, 0.8.0, because of a small breaking change that was implemented in the generation of pointings (the position of the detector quaternion was shifted one position on the right in the call to `get_pointings`: nothing to worry about if you use named arguments, as you should!).

Please update the dependency on `litebird_sim` so that it points to `0.8.0` and test it again.

**Comment by giuspugl** [comment]
Hello, 
thanks a lot for documenting this issue so well! 

> not all the observations that we consider have the pointings stored 
why is this so? @ziotom78 any clue?

**Comment by marcobortolami** [comment]
Hi!
> why is this so? @ziotom78 any clue?

@giuspugl this is a choice that @nraffuzz and I made. We calculate the pointings once and store them only in obs_cmb, i.e. the observation with the CMB signal:
```
pointings = lbs.pointings.get_pointings(obs_cmb,
                                        spin2ecliptic_quats=sim.spin2ecliptic_quats,
                                        detector_quats=detquats,
                                        bore2spin_quat=inst.bore2spin_quat,
                                        hwp=lbs.IdealHWP(hwp_radpsec),
                                        store_pointings_in_obs=True)
```
In this way we save a lot of memory as all the other observations (fg, wn, 1/f, ...) do not have the pointings stored and we can use `pointings` or `obs_cmb.pointings` where necessary.
But, as highlighted before, by doing this it is not possible to use `save_simulation_for_madam` as there is a loop over `sim.observations` where `obs.pointings` is being used.

> @marcobortolami @nraffuzz is there a reason why the filename is the same ?

This is the name of the output map, so all the information scattered among processors should be collected for the mapmaking procedure. I believe that the name should be just one. Also, the error arises from a different file, i.e. `pnt_000_000_000_QA_050_B_00000.fits`.
In any case, I tested your suggestion but the error is the same.

**Comment by ziotom78** [comment]
Mmm, you're right, the code is not working properly with MPI. And it assumes that pointings are always saved in TODs.

I'm trying to patch the code. The first problem should not be too hard to solve, but the second one might require significant rework.

**Comment by marcobortolami** [comment]
`save_simulation_for_madam` works as expected, thanks. The issue can be closed.
